image: unixs/ruby-cmake
stages:          # List of stages for jobs and their order of execution
  - codecheck
  - test
  - deploy

codecheck:
  stage: codecheck
  script:
    - env | grep CI_
    - gem install bundler
    - bundle config set --local path 'vendor/ruby'
    - bundle install
    - bundle exec rake rubocop

test-latest:
  image: unixs/ruby-btree-tests
  stage: test
  script:
    - source ~/.rvm/scripts/rvm
    - env | grep CI_
    - gem install bundler
    - bundle config set --local path 'vendor/ruby'
    - bundle install
    - bundle exec rake cmake:build
    - bundle exec rake spec

test-legacy:
  image: unixs/ruby-btree-tests:legacy
  stage: test
  script:
    - source ~/.rvm/scripts/rvm
    - env | grep CI_
    - gem install bundler
    - bundle config set --local path 'vendor/ruby'
    - bundle install
    - bundle exec rake cmake:build
    - bundle exec rake spec

build-deploy:
  only:
    # Stable releases only
    - /^v\d+\.\d+\.\d+$/
  stage: deploy
  environment:
    name: production
  before_script:
    - export GEM_PUSH_URL="https://${GEM_PUSH_TOKEN}@${GEM_PUSH_HOST}/${GEM_PUSH_PATH}"
    - export GEM_NAME="ruby-btree.gem"
  script:
    - env | grep CI_
    - env | grep GEM_
    - gem build -o $GEM_NAME
    - curl -F package=@$GEM_NAME $GEM_PUSH_URL