stages:          # List of stages for jobs and their order of execution
  - prepare
#  - build
#  - test
#  - deploy

prepare-job:
  stage: prepare
  script:
    - sudo apt update
    - sudo apt -y upgrade
    - sudo apt-get -y install pkg-config cmake libglib2.0-dev build-essentials
    - gem install bundler
    - bundle install 

#build-job:
#  stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"

#test-job:
#  stage: test
#  script:
#    - echo "This job tests something"

#deploy-prod:
#  stage: deploy
#  script:
#    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#  environment: production
