stages:          # List of stages for jobs and their order of execution
  - prepare
#  - build
#  - test
#  - deploy

prepare-job:
  stage: prepare
  artifacts:
    paths:
      - $CI_PROJECT_NAME.gem
  script:
    - env | grep CI_
    - apt update
    - apt -y upgrade
    - apt-get -y install pkg-config cmake libglib2.0-dev build-essential
    - gem install bundler
    - bundle install
    - rake cmake:build
    - rake spec
    - gem build -o $CI_PROJECT_NAME.gem

#build-job:
#  stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"

#test-job:
#  stage: test
#  script:
#    - echo "This job tests something"

#deploy-prod:
#  stage: deploy
#  script:
#    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#  environment: production
