image: unixs/ruby-cmake
stages:          # List of stages for jobs and their order of execution
  - prepare
  - build
#  - test
#  - deploy

.full_cache: &full_cache
  key: '$CI_PROJECT_ID-$CI_COMMIT_REF_SLUG'
  paths:
    - vendor/ruby

bundler:
  stage: prepare
  cache:
    key: '$CI_PROJECT_ID-$CI_COMMIT_REF_SLUG'
    paths:
      - vendor/ruby
    policy: push
  only:
    changes:
      - Gemfile.log
  script: 
    - env | grep CI_
    - gem install bundler
    - bundle config set --local path 'vendor/ruby'
    - bundle install

building:
  stage: build
  cache:
    key: '$CI_PROJECT_ID-$CI_COMMIT_REF_SLUG'
    paths:
      - vendor/ruby
    policy: pull
  script:
    - env | grep CI_
    - gem install bundler
    - bundle config set --local path 'vendor/ruby'
    - rake cmake:build

prepare-job:
  when: manual
  stage: prepare
  artifacts:
    paths:
      - $CI_PROJECT_NAME.gem
  before_script:
    - mkdir ~/.gem
    - echo "---" > ~/.gem/credentials
    - |
      echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems: '${CI_JOB_TOKEN}'" >> ~/.gem/credentials
    - chmod 0600 ~/.gem/credentials # rubygems requires 0600 permissions on the credentials file
  script:
    
    - rake spec
    - gem build -o $CI_PROJECT_NAME.gem
#    - gem push $CI_PROJECT_NAME.gem --host ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/rubygems

#build-job:
#  stage: build
#  script:
#    - echo "Hello, $GITLAB_USER_LOGIN!"

#test-job:
#  stage: test
#  script:
#    - echo "This job tests something"

#deploy-prod:
#  stage: deploy
#  script:
#    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#  environment: production
