language: ruby

cache:
  bundler: true

jobs:
  fast_finish: true

dist:
  - xenial

addons:
  apt:
    update: true
    packages:
      - cmake
  homebrew:
    packages:
      - cmake

os:
  - linux
  - osx

rvm:
  - 2.6
  - 2.7
  - 3.0
  - 3.1

before_install:
  - yes | gem update --system --force
  - gem --version
  - gem install bundler

install:
  - bundle install --jobs=3 --retry=3

before_script:
  - pwd
  - rake cmake:build

script:
  - bundle exec rake rubocop
  - bundle exec rake spec
  - rake install
  - ruby -e 'require "native_btree"'

