#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_G_TREE_INSERT 1
#define HAVE_G_TREE_REPLACE 1
#define HAVE_G_TREE_NNODES 1
#define HAVE_G_TREE_LOOKUP 1
#define HAVE_G_TREE_FOREACH 1
#define HAVE_G_TREE_SEARCH 1
#define HAVE_G_TREE_DESTROY 1
#define HAVE_G_TREE_HEIGHT 1
#endif
