name: Ruby

on:
  push:
    branches:
      - master
      - dev

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os: [ubuntu, macos]
        ruby: [2.6, 2.7, 3.0, 3.1]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Codecheck
      run: bundle exec rake rubocop

    - name: Test
      run: |
        bundle exec rake cmake:build
        bundle exec rake spec
