name: Ruby

on:
  push:
    branches:
      - '*'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        os: [ubuntu, macos]
        ruby: [2.7, 3.0, 3.1, 3.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Codecheck
      run: bundle exec rake rubocop

    - name: Test Release
      run: |
        rake cmake:build
        bundle exec rake spec

    - name: Test Debug with coverage
      run: |
        bundle exec rake cmake:rmbuild
        CMAKE_BUILD_TYPE=Debug bundle exec rake cmake:build
        bundle exec rake spec

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        gcov: true
        verbose: true
      env:
        CI: true

    - name: Build & install
      if: github.ref == 'refs/heads/master'
      run: |
        rake install
        ruby -e 'require "native_btree"'
